config/routes.rb
Rails.application.routes.draw do
  resources :innings
  resources :games
  resources :teams
  devise_for :users
  root to: 'visitors#index'
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :team_bat_first, class_name: 'Team', :foreign_key => 'team_bat_first_id'
  belongs_to :team_field_first, class_name: 'Team', :foreign_key => 'team_field_first_id'

  has_many :innings, inverse_of: :game, dependent: :destroy
  accepts_nested_attributes_for :innings, allow_destroy: true, reject_if: :reject_innings

  def reject_innings(attributed)
    attributed['number'].blank?
  end
end

app/models/inning.rb
class Inning < ActiveRecord::Base
  belongs_to :game
end

app/models/team.rb
class Team < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  def index
    @games = Game.all
  end

  # GET /games/1
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
    # @game.innings.build
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  def create
    @game = Game.new(game_params)

    if @game.save
      redirect_to @game, notice: 'Game was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /games/1
  def update
    if @game.update(game_params)
      redirect_to @game, notice: 'Game was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /games/1
  def destroy
    @game.destroy
    redirect_to games_url, notice: 'Game was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def game_params
      params.require(:game).permit(
        :name,
        :team_bat_first_id,
        :team_field_first_id,
        innings_attributes: [:id, :number, :top_score, :bottom_score, :_destroy]
      )
    end
end

app/controllers/innings_controller.rb
class InningsController < ApplicationController
  before_action :set_inning, only: [:show, :edit, :update, :destroy]

  # GET /innings
  def index
    @innings = Inning.all
  end

  # GET /innings/1
  def show
  end

  # GET /innings/new
  def new
    @inning = Inning.new
  end

  # GET /innings/1/edit
  def edit
  end

  # POST /innings
  def create
    @inning = Inning.new(inning_params)

    if @inning.save
      redirect_to @inning, notice: 'Inning was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /innings/1
  def update
    if @inning.update(inning_params)
      redirect_to @inning, notice: 'Inning was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /innings/1
  def destroy
    @inning.destroy
    redirect_to innings_url, notice: 'Inning was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inning
      @inning = Inning.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def inning_params
      params.require(:inning).permit(:game_id, :number, :top_score, :bottom_score)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  def index
    @teams = Team.all
  end

  # GET /teams/1
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  def create
    @team = Team.new(team_params)

    if @team.save
      redirect_to @team, notice: 'Team was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /teams/1
  def update
    if @team.update(team_params)
      redirect_to @team, notice: 'Team was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /teams/1
  def destroy
    @team.destroy
    redirect_to teams_url, notice: 'Team was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def team_params
      params.require(:team).permit(:name)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/innings_helper.rb
module InningsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/games/_form.html.haml
= simple_nested_form_for(@game) do |f|
  = f.error_notification

  .form-inputs
    .row
      = f.input :name

    .row
      .col-sm-3
        %div.row= f.association :team_bat_first
        %div.row= f.association :team_field_first
      .col-sm-9
        - index = 1
        = f.simple_fields_for :innings do |form_inning|
          .col-sm-1
            = f.hidden_field :id
            .row.inning_index
            %div.row= form_inning.input :top_score
            %div.row= form_inning.input :bottom_score
            %div.row= form_inning.link_to_remove 'Remove Inning'
            - index = index + 1
        = f.link_to_add 'Add Inning', :innings, data: { limit: 20 }

  .form-actions
    = f.button :submit

app/views/games/edit.html.haml
%h1 Editing game

= render 'form'

= link_to 'Show', @game
\|
= link_to 'Back', games_path

app/views/games/index.html.haml
%h1 Listing games

%table.table.table-bordered
  %thead
    %tr
      %th Name
      %th Team Bat First
      %th Team Field First
      %th
      %th
      %th

  %tbody
    - @games.each do |game|
      %tr
        %td= game.name
        %td= game.team_bat_first.name
        %td= game.team_field_first.name
        %td= link_to 'Show', game
        %td= link_to 'Edit', edit_game_path(game)
        %td= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Game', new_game_path

app/views/games/new.html.haml
%h1 New game

= render 'form'

= link_to 'Back', games_path

app/views/games/show.html.haml
%p#notice= notice

%table.table.table-bordered
  %tbody
    %tr
      %th Name
      %td= @game.name
    %tr
      %th Team Bat First
      %td= @game.team_bat_first.name
    %tr
      %th Team Field First
      %td= @game.team_field_first.name

.container
  .row{:border => '1px solid red'}
    = @game.name
  .row
    .col-sm-3
      %table.table.table-bordered
        %tbody
          %tr
            %th= 'チーム名'
          %tr
            %td= @game.team_bat_first.name
          %tr
            %td= @game.team_field_first.name
    .col-sm-9
      - @game.innings.order(:number).each do |inning|
        .col-sm-1
          %table.table.table-bordered
            %tbody
              %tr
                %th= inning.number
              %tr
                %td= inning.top_score
              %tr
                %td= inning.bottom_score

= link_to 'Edit', edit_game_path(@game)
\|
= link_to 'Back', games_path

app/views/innings/_form.html.haml
= simple_form_for(@inning) do |f|
  = f.error_notification

  .form-inputs
    = f.association :game
    = f.input :number
    = f.input :top_score
    = f.input :bottom_score

  .form-actions
    = f.button :submit

app/views/innings/edit.html.haml
%h1 Editing inning

= render 'form'

= link_to 'Show', @inning
\|
= link_to 'Back', innings_path

app/views/innings/index.html.haml
%h1 Listing innings

%table.table.table-bordered
  %thead
    %tr
      %th Game
      %th Number
      %th Top score
      %th Bottom score
      %th
      %th
      %th

  %tbody
    - @innings.each do |inning|
      %tr
        %td= inning.game.name
        %td= inning.number
        %td= inning.top_score
        %td= inning.bottom_score
        %td= link_to 'Show', inning
        %td= link_to 'Edit', edit_inning_path(inning)
        %td= link_to 'Destroy', inning, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Inning', new_inning_path

app/views/innings/new.html.haml
%h1 New inning

= render 'form'

= link_to 'Back', innings_path

app/views/innings/show.html.haml
%p#notice= notice

%p
  %b Game:
  = @inning.game.name
%p
  %b Number:
  = @inning.number
%p
  %b Top score:
  = @inning.top_score
%p
  %b Bottom score:
  = @inning.bottom_score

= link_to 'Edit', edit_inning_path(@inning)
\|
= link_to 'Back', innings_path

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  %li= link_to 'Sign out', destroy_user_session_path, method: :delete
  %li= link_to 'Teams', teams_path
  %li= link_to 'Games', games_path
  %li= link_to 'Innings', innings_path
  %span.navbar-text= current_user.email
- else
  %li= link_to 'Sign in', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Baseball Scorebook'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Baseball Scorebook'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      .container
        = render 'layouts/messages'
        = yield

app/views/pages/about.html.haml
- content_for :title do
  About
%h3 About the Website
%p
  This web application was created with
  = link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/')
  from the #{link_to('RailsApps project', 'http://railsapps.github.io/')}.

app/views/visitors/index.html.haml
/ Page Content
.container
  .row
    .col-lg-12.text-center
      %h1 A Bootstrap Starter Template
      %p.lead
        A Bootstrap HTML starter template from
        = succeed "." do
          %a{:href => "http://startbootstrap.com/"} startbootstrap.com
      %ul.list-unstyled
        %li Bootstrap
        %li jQuery
  / /.row
/ /.container